### ISSUE TITLE
New git CVE changes break this GHA

### ISSUE THREAD

**Issue by Zabuzard** [mskri/check-uncommitted-changes-action#2]
Unfortunately, this GH action is broken due to a security change in git.

See the duplicate issue (with no proper solution yet) on the action you took inspiration from:

https://github.com/UnicornGlobal/has-changes-action/issues/5

**Comment by mskri** [comment]
Thanks for letting me know! I would recommend checking for changes like suggested in this comment https://github.com/UnicornGlobal/has-changes-action/issues/5#issuecomment-1126126476
